Corrected configuration scripts

diff --git a/0x0C-web_server/4-not_found_page_404 b/0x0C-web_server/4-not_found_page_404
--- a/0x0C-web_server/4-not_found_page_404
+++ b/0x0C-web_server/4-not_found_page_404
@@ -5,14 +5,18 @@
 sudo apt-get -y update
 sudo apt-get -y install nginx
 
-# allow nginx on firewall
-sudo ufw allow 'Nginx HTTP'
-
 # crete error 404 file and put desired message in it
-echo "Ceci n'est pas une page" > /usr/share/nginx/html/page_error_404.html
+echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/page_error_404.html
 
 # create 404 directive inside stes-enabled/default file
 sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default
+
+#Check if the sed command executed successfully
+if [ $? -ne 0 ]; then
+	echo "Custom 404 page not successfully configured" >&2
+else
+	echo "Successfully configured custom 404 page"
+fi
 
 # restart nginx
 sudo service nginx restart
